%%
% Converts a matrix of traces (such as generated by importCSV.m) into a
% binary matrix of spiking events and a cell array of individual spike
% times per ROI.
%   Input: Traces - Matrix of traces
%          thrTraces - Threshold for F/F0
%          thrDiffTraces - Threshold for dF/F0/dt
%   Output:raster - binary matrix of spike events
%          SpTimes - cell array of spike times per ROI
%
function [raster , SpTimes] = TracesToSpikeTimes(Traces , thrTraces , thrDiffTraces)
    diffTraces = diff(Traces);
    try
        raster = (Traces > thrTraces) .* [zeros(1,size(Traces,2));(diffTraces > thrDiffTraces)];
    catch
        disp('oops')
    end
    SpTimes = cell(size(Traces,2),1);
    for ii = 1:size(Traces,2)
        SpTimes{ii} = find(raster(:,ii));
    end
end